version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - .env.local  # Load dari file environment
    environment:
      - GIN_MODE=debug
    networks:
      - portfolio-network
    volumes:
      - .:/app
      - go-modules:/go/pkg/mod

networks:
  portfolio-network:
    driver: bridge

volumes:
  go-modules: