name: Deploy to cPanel

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Go
      uses: actions/setup-go@v3
      with:
        go-version: '1.21'

    - name: Build Go application
      run: |
        go mod download
        go build -o main ./cmd/api

    - name: Install SSH key
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Deploy to cPanel via SSH
      run: |
        # Copy files to server
        scp -o StrictHostKeyChecking=no \
            main \
            .env \
            ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:~/app/
        
        # Restart application
        ssh -o StrictHostKeyChecking=no \
            ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} \
            "cd ~/app && ./restart.sh"